### ISSUE TITLE
No word wrap on legend

### ISSUE THREAD

**Issue by craig-shenton** [nhsx/open-health-statistics#17]
@adamivisonnhs Hi, I've tried a few fixes:
```
fig.update_layout(
    legend=dict(orientation="h"),
)
```
Is one option, but squishes the chart and seems a bit redundant with the table right below.

**Comment by craig-shenton** [comment]
I've published the page with the legend hidden to see how it looks. Not great for accessibility but not sure the chart is ever going to be, especially if we end up with ~100 organisations.

**Comment by adamivisonnhs** [comment]
Hi @craig-shenton - just got back from a weeks AL sorry about the delay... yes the graph looks better with the legend than it did without but as you say it's bad for accessibility and as the number of organisations grow it would only get more complex.

The only way I can think to improve is by finding a way to:

* Force the legend word wrap 
* Force the legend size to X% of the full width (maybe 20% to start with)
* Ensure that the legend scrolls vertically
* Force the table to the full width

I will take a look when I have some free time if this sounds like it would be a benefit?

**Comment by craig-shenton** [comment]
Hi nps @adamivisonnhs, that would be great. Think making the table a separate plotly chart would be an easy fix for the last point.

I can't find anything to set to the legend size (other than using a small font). Might be worth just using the github/lab username instead of the full name as a bit of a compromise.

Thanks,
Craig.

**Comment by adamivisonnhs** [comment]
@craig-shenton what are your thoughts...

1. Split the table out again into a separate object (sorry didn't realise at the time this was why you did it).

2. Force the text to wrap at 16 characters when adding the trace:
- https://community.plotly.com/t/scatter-plot-how-to-wrap-legends-text-when-legend-text-is-too-long/4767
- If we look at the table, currently the `Org` column cuts text at 11 to 15 (or 16) characters depending on the screen width
- This would mean the legend would be at most ~ 1.5 to 2 table columns wide.

If this doesn't look good then I think we should go with your suggestion and revert back to the usernames?

**Comment by craig-shenton** [comment]
Hi yes sounds good. Could also add the ellipses as suggested with something like [textwrap](https://docs.python.org/3/library/textwrap.html), e.g., 
```
textwrap.shorten("Nottinghamshire Healthcare NHS Foundation Trust's CDU Data Science Team", width=16, placeholder="...")
```

**Comment by adamivisonnhs** [comment]
Made the fixes and they are in a pull request now

**Comment by craig-shenton** [comment]
Works great, thanks @adamivisonnhs
