### ISSUE TITLE
Github Actions Workflow failure

### ISSUE THREAD

**Issue by maryamanuelnhsx** [nhsx/open-health-statistics#19]
@craig-shenton  - flagging that the github action workflow is [failing](https://github.com/nhsx/open-health-statistics/actions/runs/829872122), any ideas on how to resolve?
![image](https://user-images.githubusercontent.com/73167040/117852480-44375600-b27f-11eb-952a-15e00024b41c.png)

<img width="983" alt="Screenshot 2021-05-11 at 17 33 48" src="https://user-images.githubusercontent.com/73167040/117852284-12be8a80-b27f-11eb-9051-c385ffd1cd4b.png">

**Comment by craig-shenton** [comment]
Thanks Mary, think we just need to add a YAML library in the requirements.txt for the GitHub actions workflow see: 199061c

**Comment by craig-shenton** [comment]
@maryamanuelnhsx workflow is up and running again :)

**Comment by maryamanuelnhsx** [comment]
Great! thanks @craig-shenton 😃
