### ISSUE TITLE
[Accessibility]  Repeated colours in legend + charts

### ISSUE THREAD

**Issue by maryamanuel1** [nhsx/open-health-statistics#24]
Hey @adamivisonnhs, @craig-shenton, 

Seems that some of the colours in the chart are repeating  - with two orgs having the same colour pallet, which could be problem from an accessibility perspective. Is this something that we can change?

![image](https://user-images.githubusercontent.com/73167040/119478065-67660900-bd47-11eb-810d-f44f17381f0c.png)

**Comment by adamivisonnhs** [comment]
@maryamanuelnhsx its definitely fixable...

The range of `px.colors.qualitative` plotly colour palettes can be found [here](https://plotly.com/python/discrete-color/):

![image](https://user-images.githubusercontent.com/66741381/119501156-8329d900-bd60-11eb-9cc1-1519192c106c.png)

Currently we are using the default (top row) which contains 10 colours - we have 17 Orgs at the moment so this is why there is a repetition. We can combine palettes from ^^ or create our own custom palettes by defining the individual CSS colours.

Not sure which would look best from an accessibility perspective?

**Comment by maryamanuelnhsx** [comment]
Thank you @adamivisonnhs! 

I just had a chat with @craig-shenton - As an interim fix, we will use `Dark24`. Once we find more accessible colours - we will import that as our own custom palettes by defining the individual CSS colours as you say. 

I will update the colours this week and send over pull request.

Mary
