### ISSUE TITLE
Add BHF Data Science Centre

### ISSUE THREAD

**Issue by tomlincr** [nhsx/open-health-statistics#31]
Great initiative, well done 👏 

Would it be possible to add the [BHF Data Science Centre](https://github.com/BHFDSC) github organisation please?

All the CVD-COVID-UK/COVID-IMPACT projects are required to share their code and as much of this work is done in the NHS Digital TRE it may be useful to the NHS data science community. 

With thanks and all good wishes
Chris

**Comment by craig-shenton** [comment]
Hi, thanks Chris. I can add BHF no problems.

**Comment by tomlincr** [comment]
Thanks @craig-shenton, appreciate such a rapid response!
