### ISSUE TITLE
Plotly chart autoscale problem

### ISSUE THREAD

**Issue by craig-shenton** [nhsx/open-health-statistics#7]
#6 Setting Plotly chart `autosize=False` stops chart dynamically resizing and causes issues at small page widths. But `autosize=True` limits chart size to 450px

**Comment by adamivisonnhs** [comment]
Sounds like this should have solved it back in plotly 3.8 https://github.com/plotly/plotly.py/issues/1524

**Comment by adamivisonnhs** [comment]
Hi Craig,

I am struggling to find a way to output the final webpage and recreate the plot not resizing...

When I test locally with:
```
# Asthetics of the plot
fig.update_layout(
    {"plot_bgcolor": "rgba(0, 0, 0, 0)", "paper_bgcolor": "rgba(0, 0, 0, 0)"},
    autosize=False,
    height=1000,
    hovermode="x",
)
```
it fails...

When I test locally with:
```
# Asthetics of the plot
fig.update_layout(
    {"plot_bgcolor": "rgba(0, 0, 0, 0)", "paper_bgcolor": "rgba(0, 0, 0, 0)"},
    autosize=True,
    height=1000,
    hovermode="x",
)
```
it works...

Although, I did find this https://stackoverflow.com/questions/42893446/how-to-fit-map-to-width-with-plotly-python which states that `autosize` and `margin` should be used in tandem with eachother... so it might be worth trying something like:
```
fig.update_layout(
    {"plot_bgcolor": "rgba(0, 0, 0, 0)", "paper_bgcolor": "rgba(0, 0, 0, 0)"},
    autosize=True,
    margin=dict(l=50, r=50, b=50, t=50, pad=4, autoexpand=True ),
    height=1000,
    hovermode="x",
)
```

**Comment by adamivisonnhs** [comment]
> Thanks Adam the last one worked like a charm.
> 
> Craig.

No worries - it looks great now
